channels:
  - conda-forge

dependencies:
  - python=3.10
  # Machine Learning & GPU
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-gpu
  - pytorch_geometric
  # Data & Math
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - sympy
  - mpmath
  - pulp
  # Visualisation & Logs
  - matplotlib
  - seaborn
  - jupyterlab
  - tqdm
  - rich
  # Outils de dev (Analyse statique, Formatage, Tests)
  - pytest
  - ruff
  - mypy
  - pre-commit
  - pip
  - pip:
      - -e .
